### ISSUE TITLE
AttributeError for use of not_valid_before_utc

### ISSUE THREAD

**Issue by dspruell** [dspruell/tls-probe#7]
```
$ tls-probe -z 2.56.127.241 443
Traceback (most recent call last):
  File "/home/user/.local/bin/tls-probe", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/.local/pipx/venvs/tls-probe/lib/python3.11/site-packages/tls_probe.py", line 145, in cli
    conn_info = get_sock_info(
                ^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/tls-probe/lib/python3.11/site-packages/tls_probe.py", line 88, in get_sock_info
    "not_valid_before": str(cert_data.not_valid_before_utc),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cryptography.hazmat.bindings._rust.x509.Certificat' object has no attribute 'not_valid_before_utc'. Did you mean: 'not_valid_before'?
```

**Comment by dspruell** [comment]
This error occurs when the installed version of the [cryptography](https://pypi.org/project/cryptography/) library is outdated and doesn't support the timezone-aware attributes `not_valid_before_utc()` and `not_valid_before_utc()` (introduced in 42.0.0).
